### ISSUE TITLE
Bug in ViewController.swift JSON communication

### ISSUE THREAD

**Issue by kliess** [IBM/watson-waste-sorter#22]
If you run the current code you have to change https://github.com/IBM/watson-waste-sorter/blob/b49b8e51b52a1ebfc993c48b60f247e880f54d53/mobile-app/WatsonWasteSorter/ViewController.swift#L56

from

 if let confs = JSON["confident score"] as? Float {

to

if let confs = JSON["confident score"] as? Double{

The reason of this bug is maybe a change on the server side, but this will fix it on the client side.

**Comment by scottdangelo** [comment]
What is the nature of the failure? Can you post the error signature?

**Comment by kliess** [comment]
If you set a breakpoint on this line you can see that the JSON NSDictionary object has the following value:

[1]	(null)	"confident score" : Double(0.621)	
key	__NSCFString *	"confident score"	0x00000001c0455600
value	__NSCFNumber *	Double(0.621)	0x00000001c003f880

The Double value will not be cast to a float value, so the line is never true and the showAlert will be never executed.
