### ISSUE TITLE
image result not classified correctly

### ISSUE THREAD

**Issue by jouhyoung** [IBM/watson-waste-sorter#33]
Hi
    I followed Step 1 and 2 to create my application server and deployed to cloud foundry. 
As I take images through my devices the classified results were of different colors, instead of the different categories.
Below is the result I get in xcode console.
```
2019-04-29 17:26:39.851877-0700 WatsonWasteSorter[512:25891] [MC] Reading from public effective user settings.
{
    "confident score" = "0.884";
    result = "emerald color";
    "status code" = 200;
}
```

Please let me know if there's something that I've done incorrectly.
Thanks!

**Comment by stevemar** [comment]
@jouhyoung in the logs, can you tell which version of the sdk is installed? the watson sdk team just released a new major version that breaks things, i suspect this repo is affected. i will propose that we cap the requirement to <3.0.0 for now.
