### ISSUE TITLE
TODO after meeting on 1/12/2018

### ISSUE THREAD

**Issue by stevemar** [IBM/watson-waste-sorter#6]
1. Create a mobile front-end. Suggest using Cordova to create since it can produce content that will work on both Android and iOS. See https://github.com/IBM/watson-vehicle-damage-analyzer/tree/master/mobile as an example. @XiaoguangMo agreed to give the rest of the team a one hour education session on how to demonstrate a quick app built locally and run on an iPhone.
2. Add a "deploy to bluemix" button -- See https://github.com/IBM/watson-vehicle-damage-analyzer/blob/master/server/lib/watson-visRec-setup.js as an example. This will automatically create a classifier based on content checked into the repo.
3. More pictures! These should be checked into the repo.

**Comment by stevemar** [comment]
cc @XiaoguangMo @Tomcli @liuweiwei10 @hezhuusc

**Comment by ghost** [comment]
I was just browsing through IBM projects and found this. This is a great idea for an app. I had been recently thinking about a similar more focused idea to scavenge high value reusable electronics components from recycled/broken equipment. In particular re-programmable chips like FPGA's, CPLDs and EEPROMS. I see you are targeting a more general use case which is very much needed if we are going to get a handle on the amount of (e)waste we generate.

**Comment by stevemar** [comment]
thank for the feedback @rgjones33 ! you're right in saying that it's a more general use case but i'm excited to see how this project turns out!

**Comment by stevemar** [comment]
Closing this for now, the first two issues were resolved in other PRs and the last one is a nice stretch goal.
